# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
    - master

jobs:
- job: build_and_test
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    workingDirectory: my-app
    displayName: 'npm install and build'

  - script: |
      npx cypress verify
    workingDirectory: my-app
    displayName: 'Verify cypress'

  - script: |
      npm run start-server-and-test:silent
    workingDirectory: my-app
    displayName: 'start server and launch cypress tests'


  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/my-app/cypress/videos'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/cypress-videos'
      CleanTargetFolder: true
      OverWrite: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/cypress-videos'
      ArtifactName: 'cypress-videos'
      publishLocation: 'Container'


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/my-app/cypress/cucumber-json'
      ArtifactName: 'pickles-json'
      publishLocation: 'Container'

- job: generate_pickles_doc
  dependsOn:
  - build_and_test
  condition: succeeded('build_and_test')
  pool:
      vmImage: windows-latest
  steps: 
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: pickles-json
      downloadPath: $(System.DefaultWorkingDirectory)

  - task: Pickles@2
    inputs:
      featureDir: '$(System.DefaultWorkingDirectory)/my-app/cypress/integration/examples/features'
      resultsFile: '$(System.DefaultWorkingDirectory)/pickles-json/**'
      resultsFormat: CucumberJson
      docFormat: Html
      out: '$(System.DefaultWorkingDirectory)/pickles'
      language: 'fr'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/pickles'
      ArtifactName: 'pickles-living-doc'
      publishLocation: 'Container'
